services:
    laravel:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel
        environment:
            PHP_OPCACHE_ENABLE: 1
            PRODUCTION: 0
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./storage:/var/www/html/storage
        healthcheck:
            test: ["CMD", "curl", "-f", "http://laravel/up"]
            interval: 30s
            timeout: 10s
            retries: 3
        networks:
            - sail
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
